<?php

require_once "includes/tripal_analysis_kegg.heir_parser.inc";
require_once "includes/tripal_analysis_kegg.chado_node.inc";
require_once "theme/tripal_analysis_kegg.theme.inc";

/*******************************************************************************
 *
******************************************************************************/

function tripal_analysis_kegg_init() {
  // add the tripal_analysis_kegg JS and CSS
  drupal_add_js(drupal_get_path('module', 'tripal_analysis_kegg') . '/theme/js/tripal_analysis_kegg.js');
  drupal_add_css(drupal_get_path('module', 'tripal_analysis_kegg') . '/theme/css/tripal_analysis_kegg.css', 'theme');
}

/*******************************************************************************
 * Menu items are automatically added for the new node types created
* by this module to the 'Create Content' Navigation menu item.  This function
* adds more menu items needed for this module.
*/
function tripal_analysis_kegg_menu() {

  // ajax and non-javascript callbacks for retrieving KEGG report data
  $items['tripal_analysis_kegg/report/nojs/%/%'] = array(
    'page callback' => 'tripal_analysis_kegg_brite_ajax_update',
    'page arguments' => array(3, 4),
    'access arguments' => array('access chado_analysis_kegg content'),
    'type' => MENU_CALLBACK
  );
  $items['tripal_analysis_kegg/report/ajax/%/%'] = array(
    'delivery callback' => 'ajax_deliver',
    'page callback' => 'tripal_analysis_kegg_brite_ajax_update',
    'page arguments' => array(3, 4),
    'access arguments' => array('access chado_analysis_kegg content'),
    'type' => MENU_CALLBACK
  );
  return $items;
}
/*******************************************************************************
 * Set the permission types that the chado module uses.  Essentially we
* want permissionis that protect creation, editing and deleting of chado
* data objects
*/
function tripal_analysis_kegg_permissions() {
  return array(
      'access chado_analysis_kegg content' => array(
        'title' => t('View Chado Analysis Blast'),
        'description' => t('Allow users to view chado analysis blast pages.'),
      ),
      'create chado_analysis_kegg content'=> array(
        'title' => t('Create Chado Analysis Blast'),
        'description' => t('Allow users to create new chado analysis blast pages.'),
      ),
      'delete chado_analysis_kegg content'=> array(
        'title' => t('Delete Chado Analysis Blast'),
        'description' => t('Allow users to delete chado analysis blast pages.'),
      ),
      'edit chado_analysis_kegg content' => array(
      'title' => t('Edit Chado Analysis Blast'),
      'description' => t('Allow users to edit chado analysis blast pages.'),
    ),
  );
}



/**
 *
 *
 * @ingroup tripal_analysis_kegg
 */
function tripal_analysis_kegg_block($op = 'list', $delta = 0, $edit=array()) {
  switch ($op) {
    case 'list':
      $blocks['featurekegg']['info'] = t('Tripal Feature KEGG Terms');
      $blocks['featurekegg']['cache'] = BLOCK_NO_CACHE;

      $blocks['orgkegg']['info'] = t('Organism KEGG Summary');
      $blocks['orgkegg']['cache'] = BLOCK_NO_CACHE;

      $blocks['kegg_base']['info'] = t('Analsyis: KEGG Details');
      $blocks['kegg_base']['cache'] = BLOCK_NO_CACHE;

       
      return $blocks;


    case 'view':
      if (user_access('access chado_analysis_kegg content') and arg(0) == 'node' and is_numeric(arg(1))) {
        $nid = arg(1);
        $node = node_load($nid);

        $block = array();
        switch ($delta) {
          case 'featurekegg':
            $block['subject'] = t('KEGG Terms');
            $block['content'] = theme('tripal_feature_kegg_terms', $node);
            break;

          case 'orgkegg':
            $block['subject'] = t('KEGG Terms');
            $block['content'] = theme('tripal_organism_kegg_summary', $node);
            break;

          case 'kegg_base':
            $block['subject'] = t('KEGG Terms');
            $block['content'] = theme('tripal_analysis_kegg_report', $node);
            break;

          default :
        }
        return $block;
      }
  }
}

/************************************************************************
 *  We need to let drupal know about our theme functions and their arguments.
*  We create theme functions to allow users of the module to customize the
*  look and feel of the output generated in this module
*/
function tripal_analysis_kegg_theme($existing, $type, $theme, $path) {

  $core_path = drupal_get_path('module', 'tripal_core');
  $items = array (
      'node__chado_analysis_kegg' => array (
          'template' => 'node--chado-generic',
          'render element' => 'node',
          'base hook' => 'node',
          'path' => "$core_path/theme"
      ),
      'tripal_analysis_kegg_base' => array(
          'variables' => array('node' => NULL),
          'template' => 'tripal_analysis_kegg_base',
          'path' => "$path/theme/tripal_analysis_kegg",
      ),
      'tripal_analysis_kegg_teaser' => array(
          'variables' => array('node' => NULL),
          'template' => 'tripal_analysis_kegg_teaser',
          'path' => "$path/theme/tripal_analysis_kegg",
      ),
      'tripal_analysis_kegg_report' => array(
          'variables' => array('node' => NULL),
          'template' => 'tripal_analysis_kegg_report',
          'path' => "$path/theme/tripal_analysis_kegg",
      ),

      // tripal_organism theme
      'tripal_organism_kegg_summary' => array(
          'variables' => array('node' => NULL),
          'template' => 'tripal_organism_kegg_summary',
          'path' => "$path/theme/tripal_organism",
      ),
  );
  
  return $items;
}

/**
 * 
 * @param unknown $node
 */
function tripal_analysis_kegg_organism_results($node) {
  $node = node_load($node);
  return tripal_analysis_kegg_organism_add($node);
}

/**
 * Implementation of hook_form_alter()
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 *
 */
function tripal_analysis_kegg_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == "chado_analysis_kegg_node_form") {
    // turn off preview button for insert/updates
    $form['actions']['preview']['#access'] = FALSE;
  }
}